logging.level:
  root: INFO

  org:
    zalando:
      logbook: INFO

spring:
  main:
    banner-mode: off

  sql:
    init:
      mode: always

  datasource:
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: none
