CREATE TABLE IF NOT EXISTS Genre
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(255) NOT NULL UNIQUE,
    name     VARCHAR(255),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS Rating
(
    rating_id   INTEGER PRIMARY KEY,
    rating_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Films
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    release_date DATE,
    duration     INTEGER CHECK (duration > 0),
    rating_id    INTEGER,
    FOREIGN KEY (rating_id) REFERENCES Rating (rating_id)
);

CREATE TABLE IF NOT EXISTS Friendship
(
    user_id   BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES Users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Likes
(
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, film_id),
    FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE,
    FOREIGN KEY (film_id) REFERENCES Films (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Film_genre
(
    film_id  BIGINT  NOT NULL,
    genre_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES Films (id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES Genre (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS directors
(
	director_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar(255) NOT NULL,
	CONSTRAINT directors_pk PRIMARY KEY (director_id)
);

CREATE TABLE IF NOT EXISTS film_directors
(
	id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	film_id BIGINT NOT NULL,
	director_id BIGINT NOT NULL,
	CONSTRAINT film_directors_pk PRIMARY KEY (id),
    FOREIGN KEY (film_id) REFERENCES Films (id) ON DELETE CASCADE,
    FOREIGN KEY (director_id) REFERENCES directors (director_id) ON DELETE CASCADE
);