CREATE TABLE IF NOT EXISTS Genre
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(255) NOT NULL UNIQUE,
    name     VARCHAR(255),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS Films
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT,
    release_date DATE,
    duration     INTEGER,
    rating_id    INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Friendship
(
    user_id   BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES Users (id),
    FOREIGN KEY (friend_id) REFERENCES Users (id)
);

CREATE TABLE IF NOT EXISTS Likes
(
    user_id BIGINT NOT NULL,
    film_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, film_id),
    FOREIGN KEY (user_id) REFERENCES Users (id),
    FOREIGN KEY (film_id) REFERENCES Films (id)
);

CREATE TABLE IF NOT EXISTS Film_genre
(
    film_id  BIGINT  NOT NULL,
    genre_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES Films (id),
    FOREIGN KEY (genre_id) REFERENCES Genre (id)
);

CREATE TABLE IF NOT EXISTS Rating
(
    rating_id   BIGINT NOT NULL,
    rating_name VARCHAR(225)
);

INSERT INTO Rating(rating_id, rating_name)
VALUES (1, 'G'),
       (2, 'PG'),
       (3, 'PG_13'),
       (4, 'R'),
       (5, 'NC_17');
